runtime:
  distribution_strategy: 'mirrored'
  num_gpus: 1
  batchnorm_spatial_persistent: True
train_dataset:
  name: 'cifar10'
  data_dir: null
  builder: 'cifar10/3.0.2/records'
  split: 'train'
  path: 'cifar10-train'
  image_size: 32
  num_classes: 10
  num_examples: 50000
  batch_size: 128
  use_per_replica_batch_size: True
  dtype: 'float16'
  mean_subtract: True
  standardize: True
validation_dataset:
  name: 'cifar10'
  data_dir: null
  builder: 'records'
  split: 'test'
  path: 'cifar10/3.0.2/cifar10-test'
  image_size: 32
  num_classes: 10
  num_examples: 10000
  batch_size: 128
  use_per_replica_batch_size: True
  dtype: 'float16'
  mean_subtract: True
  standardize: True
model:
  name: 'resnet'
  model_params:
    rescale_inputs: False
  optimizer:
    name: 'momentum'
    momentum: 0.9
    decay: 0.9
    epsilon: 0.001
  loss:
    label_smoothing: 0.1
train:
  resume_checkpoint: True
  epochs: 90
evaluation:
  epochs_between_evals: 1
